name:                haskari
version:             0.1.0.0
github:              "githubuser/haskari"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A simple Akari solver
category:            Puzzle,Solver

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskari#readme>

dependencies:
- base >= 4.7 && < 5
- ersatz
- containers
- vector
- transformers
- foldl-extras
- mtl
- foldl
- transformers
- mtl
- lens
- unordered-containers
- union-find
- hashable
- profunctors

ghc-options:
- -Wall


library:
  source-dirs: src

executables:
  haskari-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskari

tests:
  haskari-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskari
